### ISSUE TITLE
Use this code with other EPOS devices?

### ISSUE THREAD

**Issue by ghost** [brtiberio/EPOS_Canopen#2]
I have an EPOS4 50/5 controller and would like to use your code to control it. Is it possible to modify your code to make this work?
Thanks

**Comment by patrickw135** [comment]
I have exactly the same project running and wondering ;)

My setup: 
Raspberry Pi 3B+, CAN-HAT (CAN-to-SPI), EPOS 50/5 & EPOS 24/2

Thanks

**Comment by brtiberio** [comment]
Hello!
When I was reading documentation from Maxon I remember that many commands where shared among several devices. So I would say it is possible to be pretty much compatible or at least very similar. Canopen also defines a few dictionary words that must be respected by all manufacturers if they want to comply with a specific profile definition. Like the 402 profile.

**Comment by brtiberio** [comment]
As for modification, yes of course. Feel free to do so. If later on you can share you improvements with this repository, please feel free to do a pull request. 
However I am no longer able to test in real devices because I am no longer working in this field.
